name: "Code Owner Approval Workflow"

on:
  pull_request_review:
    types: [submitted]

jobs:
  codeowners-approval:
    runs-on: ubuntu-latest
    steps:
      - name: Check Code Owner Approval
        uses: noamelf/codeowner-approval-action@main 
        with:
          pr-number: ${{ github.event.pull_request.number }}
          repo-name: ${{ github.repository }}
          github-token: ${{ secrets.MY_GITHUB_TOKEN }}
