name: "Reusable Code Owner Approval Workflow"

on:
  workflow_call:
    inputs:
      pr-number:
        required: true
        type: number
      repo-name:
        required: true
        type: string
      app-id:
        required: true
        type: string
    secrets:
     app-private-key:
        required: true

jobs:
  codeowners-approval:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/create-github-app-token@v1
      id: app-token
      with:
        app-id: ${{ inputs.app-id }}
        private-key: ${{ secrets.app-private-key }}
        owner: ${{ github.repository_owner }}
    - name: Check Code Owner Approval
      uses: noamelf/codeowner-approval-action@main 
      with:
        pr-number: ${{ github.event.pull_request.number }}
        repo-name: ${{ github.repository }}
      env:
        GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
