name: "Create a PR as a bot"

on:
  workflow_dispatch: # Allows you to manually trigger the workflow

jobs:
  create_pull_request:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Update AUTHORS
      run: |
        git log --format='%aN <%aE>%n%cN <%cE>' | sort -u >> AUTHORS

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v6
      with:
        commit-message: update authors
        title: Update AUTHORS
        body: Credit new contributors by updating AUTHORS
        branch: update-authors